name: voice_segmentation
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.1
  - torchaudio
  - numpy
  - pandas
  - tqdm
  - pip
  - pip:
      - speechbrain
      - requests
      - soundfile
      - huggingface_hub==0.19.4
      - scikit-learn